coverage:
  status:
    project:
      api:
        target: auto
        flags:
          - api
      # app2:
      #   target: auto
      #   flags:
      #     - app2

flags:
  api:
    paths:
      - coverage/apps/api/coverage-final.json
    carryforward: true
  # app2:
  #   paths:
  #     - coverage/apps/app2/coverage-final.json
  #   carryforward: true
