coverage:
  status:
    project:
      default:
        target: auto
      api:
        target: auto
        flags:
          - api
      # app2:
      #   target: auto
      #   flags:
      #     - app2

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null

flags:
  api:
    paths:
      - apps/api/
    carryforward: true
  # app2:
  #   paths:
  #     - apps/app2/
  #   carryforward: true

